USE GD1C2025
GO

----- ELIMINACION DE TABLAS -----
IF OBJECT_ID('JOIN_FORCES.provincia', 'U') IS NOT NULL
    DROP TABLE JOIN_FORCES.provincia
IF OBJECT_ID('JOIN_FORCES.localidad', 'U') IS NOT NULL
    DROP TABLE JOIN_FORCES.localidad
IF OBJECT_ID('JOIN_FORCES.direccion', 'U') IS NOT NULL
    DROP TABLE JOIN_FORCES.direccion
IF OBJECT_ID('JOIN_FORCES.estado', 'U') IS NOT NULL
    DROP TABLE JOIN_FORCES.estado
GO


----- ESQUEMA JOIN_FORCES -----
CREATE SCHEMA JOIN_FORCES
GO

----- TABLAS -----
CREATE TABLE JOIN_FORCES.provincia(
    id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    nombre NVARCHAR(255) NOT NULL,
)

CREATE TABLE JOIN_FORCES.localidad(
    id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    nombre NVARCHAR(255) NOT NULL,
    provincia_id INT NOT NULL,
    FOREIGN KEY (provincia_id) REFERENCES JOIN_FORCES.provincia(id)
)

CREATE TABLE JOIN_FORCES.direccion(
    id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    nombre NVARCHAR(255) NOT NULL,
    localidad_id INT NOT NULL,
    FOREIGN KEY (localidad_id) REFERENCES JOIN_FORCES.localidad(id)
)

CREATE TABLE JOIN_FORCES.estado(
    id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    nombre NVARCHAR(255) NOT NULL,
)